# Generated by Django 6.0.1 on 2026-02-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('species', models.CharField(choices=[('dog', 'Pies'), ('cat', 'Kot'), ('other', 'Inne')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('is_adopted', models.BooleanField(default=False)),
            ],
        ),
    ]
